### PR TITLE
Add PhoneNumber Encoder/Decoder Docs and Fix OTC Entry Paste Issue

### LINKED ISSUE #99: Autofill Phone Number Verification Code
### Description

When receiving a verification code for the phone number feature in Spezi Account it only starts to fill in the first digit and doesn’t jump to the next text field.

### Reproduction

Paste in a 6 digit code in the code verification field using the keyboard autofill feature.

### Expected behavior

The keyboard autofill feature should be using as expected. It potentially means that we combine the entry in a single text field with some additional formatting similar to Spezi Access Guard.

### Additional context

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct and Contributing Guidelines

### PR DESCRIPTION
**Pull request by NikolaiMadlener**
# *Add PhoneNumber Encoder/Decoder Docs and Fix OTC Entry Paste Issue*

## :recycle: Current situation & Problem
#99 

## :gear: Release Notes
- Extend setup docs of phone numbers key with optional encoder/decoder setup step
- Fix #99 by changing the individual pin Textfields to one Textfield with pin overlays

## :pencil: Code of Conduct & Contributing Guidelines
By creating and submitting this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: Sources/SpeziAccountPhoneNumbers/DataEntry/OTCEntryView.swift [hunk 1]
```diff
@@ -120,36 +80,62 @@ struct OTCEntryView: View {
...
+                        pinDigit(index: index)
+                    }
+                }
+            )
+            .accessibilityLabel("Verification code entry")
+#if !os(macOS)
+            .keyboardType(.numberPad)
+            .textContentType(.oneTimeCode)
+#endif
+            .onChange(of: verificationCode) { _, newValue in
```
Comment (PSchmiedmayer) [inline Sources/SpeziAccountPhoneNumbers/DataEntry/OTCEntryView.swift:108]: We probably also need to handle the case what happens if a user enters more digits that the ones provided and/or if we paste in a code that is longer than the expected one time code?

File: Sources/SpeziAccountPhoneNumbers/DataEntry/OTCEntryView.swift
Comment (PSchmiedmayer) [inline Sources/SpeziAccountPhoneNumbers/DataEntry/OTCEntryView.swift:1]: Thank you for the improvements here; thank you for working on this 🚀

File: Sources/SpeziAccountPhoneNumbers/SpeziAccountPhoneNumbers.docc/SpeziAccountPhoneNumbers.md [hunk 2]
```diff
@@ -34,6 +34,41 @@ var configuredValues: AccountValueConfiguration {
 }
 ```
 
+1.1 (Optional) Configure custom encoding/decoding strategy for SpeziFirebase storage:
```
Comment (PSchmiedmayer) [inline Sources/SpeziAccountPhoneNumbers/SpeziAccountPhoneNumbers.docc/SpeziAccountPhoneNumbers.md:37]: I would suggest to make the general explanation independent of Firebase and the `FirestoreAccountStorage` example. Maybe let's start with a general motivation and then transition to the example that says "hey, if you, e.g., use Firebase, here is an example:"

File: Sources/SpeziAccountPhoneNumbers/SpeziAccountPhoneNumbers.docc/SpeziAccountPhoneNumbers.md [hunk 3]
```diff
@@ -34,6 +34,41 @@ var configuredValues: AccountValueConfiguration {
...
+    let encoder = FirebaseFirestore.Firestore.Encoder()
+    encoder.userInfo[CodingUserInfoKey(rawValue: "com.roymarmelstein.PhoneNumberKit.encoding-strategy")!] = PhoneNumberDecodingStrategy.e164
+    return encoder
+}
+
+private var customDecoder: FirebaseFirestore.Firestore.Decoder {
+    let decoder = FirebaseFirestore.Firestore.Decoder()
+    decoder.userInfo[CodingUserInfoKey(rawValue: "com.roymarmelstein.PhoneNumberKit.decoding-strategy")!] = PhoneNumberDecodingStrategy.e164
+    return decoder
+}
```
Comment (PSchmiedmayer) [inline Sources/SpeziAccountPhoneNumbers/SpeziAccountPhoneNumbers.docc/SpeziAccountPhoneNumbers.md:69]: Good example here with a configuration example. Probably want to make this constants and move them above the configuration.
```suggestion
private let customEncoder: FirebaseFirestore.Firestore.Encoder {
    let encoder = FirebaseFirestore.Firestore.Encoder()
    encoder.userInfo[.phoneNumberEncodingStrategy] = PhoneNumberDecodingStrategy.e164
    return encoder
}()

private var customDecoder: FirebaseFirestore.Firestore.Decoder {
    let decoder = FirebaseFirestore.Firestore.Decoder()
    decoder.userInfo[.phoneNumberDecodingStrategy] = PhoneNumberDecodingStrategy.e164
    return decoder
}()
```

**Review by PSchmiedmayer — APPROVED** [review]
Thank you for all the improvements here; only had a few comments that also link to the Firebase PR; thank you for working on this 🚀

File: Sources/SpeziAccountPhoneNumbers/DataEntry/OTCEntryView.swift (hunk 1 above)
Comment (NikolaiMadlener) [reply Sources/SpeziAccountPhoneNumbers/DataEntry/OTCEntryView.swift:108]: I think the current implementation already handles this with `verificationCode = String(filtered.prefix(codeLength))`.

Comment (PSchmiedmayer) [reply Sources/SpeziAccountPhoneNumbers/DataEntry/OTCEntryView.swift:108]: Nice, missed that; thank you!

**Review by PSchmiedmayer — APPROVED** [review]
Looks great; happy to see this merged and embedded in ENGAGE-HF 🚀
